service: first-serverless-project

provider:
  name: aws
  runtime: nodejs10.x
  profile: therealneotamoe

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  hola:
    handler: handler.hola
    events:
      - http:
          path: hola/{name}
          method: get
  annyoung:
    handler: handler.annyoung
    events:
      - http:
          path: annyoung
          method: post